export const GET_CANDIDATES_RESPONSE = 'GET_CANDIDATES_RESPONSE';
export const GET_CANDIDATE_RESPONSE = 'GET_CANDIDATE_RESPONSE';
export const ADD_NEW_CANDIDATE_RESPONSE = 'ADD_NEW_CANDIDATE_RESPONSE';
export const UPDATE_EXISTING_CANDIDATE_RESPONSE = 'UPDATE_EXISTING_CANDIDATE_RESPONSE';
export const DELETE_CANDIDATE_RESPONSE = 'DELETE_CANDIDATE_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
